# Generated by Django 5.0.6 on 2024-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("modelo", models.CharField(blank=True, max_length=200, null=True)),
                ("marca", models.CharField(blank=True, max_length=50, null=True)),
                ("ano_lancamento", models.DateField(blank=True, null=True)),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
        ),
    ]
