# Generated by Django 5.0.6 on 2024-09-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_brand_alter_car_modelo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Marca", "verbose_name_plural": "Marcas"},
        ),
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "Carro"},
        ),
        migrations.AddField(
            model_name="car",
            name="imagens_veiculos",
            field=models.ImageField(blank=True, null=True, upload_to="App"),
        ),
        migrations.AddField(
            model_name="car",
            name="placa",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="nome",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
